---
- name: MongoDB | Fetch GPG key
  sudo: yes
  command: apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv EA312927
  tags: mongodb

- name: MongoDB | Add repository
  sudo: yes
  shell:
    echo "deb http://repo.mongodb.org/apt/ubuntu trusty/mongodb-org/3.2 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-3.2.list
  tags: mongodb

- name: MongoDB | Install latest mongodb
  sudo: yes
  apt: pkg=mongodb-org update-cache=yes
  tags: mongodb

- name: MongoDB | Push default configuration template
  sudo: yes
  template:
    src=mongod.conf.j2
    dest=/etc/mongod.conf
    owner=root group=root mode=0644
  tags: mongodb
  notify:
  - restart mongodb

- name: MongoDB | Trigger mongodb restart
  meta: flush_handlers
  tages: mongodb

- name: MongoDB | Run mongo daemon
  sudo: yes
  service: name=mongod state=restarted
  tags: mongodb
